include:
  - project: 'sdu-in-oss-analytics/eric-sdui-template-group/eric-sdui-cicd-template'
    file: '.gitlab-ci.yml'
  - project: "bdgs-security/bcss-sd-pipeline-template"
    ref: 1.1.3
    file: "sd-compliance-pipeline-template.yml" 

image: $CICD_BASE_IMAGE
stages:
  - pipeline_check
  - version
  - code-test
  - mvn-build
  - build-lib
  - codescan
  - upload-pypi
  - build-image
  - packaging
  - git-operation
  - deployment
  - cleanup
  - update_pipeline

variables:
  GITLAB_DOMAIN: "gitlab.rosetta.ericssondevops.com"
  PACKAGE_REPOSITORY: https://artifactory.rosetta.ericssondevops.com/artifactory/sdu-in-oss-analytics-helm/
  HOH_UPDATE_REQUIRED: "FALSE"
  HOH_REPOSITORY_PATH: ""
  HOH_REPO: ""
  MASTER_VERSION: "1.0.0"
  PROJECT_LANGUAGE: "PYTHON"
  REPO_TYPE: "CONFIG"
  PYPACKAGE_DIRECTORY: "eric_sdui_docgen_libcommon_py"
  PYTEST_CONFIG_FILE: "$PYPACKAGE_DIRECTORY/config_local.yaml"
  UV_TEMPLATE: "TRUE"
  UPLOAD_PYPI: "TRUE"
  DEPLOYMENT_REQUIRED: "FALSE"
  NAMESPACE: ""
  AF_FILE: "$CI_PIPELINE_ID.tar.gz"
  ACA_FILE: "$CI_PIPELINE_ID.tar.gz"
  SDCP_CUSTOM_BRANCH_EXECUTION_NAME: "dev"
  DT_API_KEY: ${DT_API_KEY}
  ENABLE_PY_BUILD:
    value: "TRUE"
    options:
      - "TRUE"
      - "FALSE"

.before_script_template:
  before_script:
    - docker login registry.rosetta.ericssondevops.com -u $Rosetta_user -p $Rosetta_pwd
    - shopt -s expand_aliases
    - . ~/.bashrc
