# Status constants
STATUS_DRAFT = "Draft"
STATUS_INPROGRESS = "In-Progress"
STATUS_FAILED = "Failed"
STATUS_BASELINE = "Baseline"
JOB_STATUS = [STATUS_DRAFT, STATUS_BASELINE]

# File status constants
FILE_STATUS_UPLOADED = "Uploaded"
FILE_STATUS_SUCCEEDED = "Succeeded"
FILE_STATUS_PROCESSED = "Processed"
FILE_STATUS_SKIPPED = "Skipped"
FILE_STATUS_INPROGRESS = "In-Progress"
FILE_STATUS_DOWNLOADED = "Downloaded"
FILE_STATUS_FAILED = "Failed"
FILE_STATUS = [
    FILE_STATUS_DOWNLOADED,
    FILE_STATUS_UPLOADED,
    FILE_STATUS_PROCESSED,
    FILE_STATUS_FAILED,
    FILE_STATUS_SKIPPED,
    FILE_STATUS_SUCCEEDED
]
FILE_STATUS_UNPROCESSED = [FILE_STATUS_UPLOADED, FILE_STATUS_FAILED]

# Configuration status
CONFIG_STATUS_READY = "Ready"

# Process status constants
PROCESS_STATUS_STARTED = "Started"
PROCESS_STATUS_SUBMITTED = "Submitted"
PROCESS_STATUS_RUNNING = "Running"
PROCESS_STATUS_COMPLETED = "Completed"
PROCESS_STATUS_FAILED = "Failed"
PROCESS_PARTIAL_SUCCEEDED = "PartialSucceeded"
PROCESS_STATUS = [
    PROCESS_STATUS_STARTED,
    PROCESS_STATUS_SUBMITTED,
    PROCESS_STATUS_RUNNING,
    PROCESS_STATUS_FAILED,
    PROCESS_STATUS_COMPLETED,
    PROCESS_PARTIAL_SUCCEEDED
]

EVENT_STATUS_RUNNING = "Running"
EVENT_STATUS_COMPLETED = "Completed"
EVENT_STATUS_FAILED = "Failed"
EVENT_STATUS_FINISHED = "Finished"

# Template types
TEMPLATE_TYPE_BASIC = "Basic"
TEMPLATE_TYPE_GENERATED = "Generated"

# Storage paths and prefixes
MN_DOC_DOMAIN_TEMPLATE = "doc-generation"

# Request types
REQUEST_TYPE_DT = "DT"
REQUEST_TYPE_KB = "KB"
REQUEST_TYPE_DOC_GENERATION = "GENERATION"
REQUEST_TYPE_DOC_BASELINE = "BASELINE"
REQUEST_TYPE_DOC_GENERATION_BASELINE = "GENERATION_AND_BASELINE"
